# **Neuromah**

**A neural network framework that you can use to train your model on!**

In [1]:
from tensorflow.keras.datasets.mnist import load_data
from Neuromah.src.core import Model
from Neuromah.src.layers import Layer_Dense
from Neuromah.src.losses.categorical_crossentropy import Loss_CategoricalCrossentropy
from Neuromah.src.optimizers import Optimizer_Adam
from Neuromah.src.activations import Activation_Softmax, Activation_ReLU
from Neuromah.src.metrics.Accuracy_Categorical import Accuracy_Categorical
import numpy as np

## **Downlaod a dataset**

**here we will use the mnist dataset since it's a hello-world for machine-learning and deep learning**


In [2]:
(train_images , train_labels) , (test_images , test_labels) = load_data()

### **retreive its X and Y shape**

In [3]:
print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)
print(test_labels.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


## **Naive normalization**

In [4]:
train_images = (train_images.astype(np.float32) / 255.0).reshape(train_images.shape[0], -1)
test_images = (test_images.astype(np.float32) / 255.0).reshape(test_images.shape[0], -1)
train_labels = np.eye(10)[train_labels]
test_labels = np.eye(10)[test_labels]

### **spliting the train-validation sets**

In [5]:
# validation data
val_images = train_images[:10000]
val_labels = train_labels[:10000]
train_images = train_images[10000:]
train_labels = train_labels[10000:]

## **Instantiating our model**

- **by february 2, 2025 Neuromah only supports the Dense (fully-connected) layer**

<br>

use model's `add` method for adding the layers to the model in the sequential manner

In [6]:
model = Model()

model.add(Layer_Dense(n_inputs=784, n_neurons=128, activation=Activation_ReLU()))
model.add(Layer_Dense(n_inputs=128, n_neurons=64, activation=Activation_ReLU()))
model.add(Layer_Dense(n_inputs=64, n_neurons=10, activation=Activation_Softmax()))
model.add(Activation_Softmax())

## **Setting**

In [7]:
model.set(
    loss=Loss_CategoricalCrossentropy(model=model),
    optimizer=Optimizer_Adam(learning_rate=0.001),  # recommended lr value for Adam
    accuracy = Accuracy_Categorical(model= model)
)

## **Finalizing the model**

- always finalize the model before trying to train it
- use Model's `finalize` method
- similar to `compile` in Keras

In [8]:
model.finalize()

## Train

- train the model using the Model's `train` method 

In [9]:
model.train(train_images, train_labels, epochs=10, batch_size=32, validation_data=(val_images, val_labels))

Epoch 1/10: 100%|████████████████████| 1563/1563 [00:13<00:00, 118.12step/s]


time: 13.25s, acc: 0.887, loss: 1.629 (data_loss: 1.629, reg_loss: 0.000), lr: 0.0010000
validation, acc: 0.888, loss: 1.575


Epoch 2/10: 100%|████████████████████| 1563/1563 [00:15<00:00, 102.92step/s]


time: 15.19s, acc: 0.929, loss: 1.540 (data_loss: 1.540, reg_loss: 0.000), lr: 0.0010000
validation, acc: 0.926, loss: 1.535


Epoch 3/10: 100%|████████████████████| 1563/1563 [00:19<00:00, 81.66step/s]


time: 19.14s, acc: 0.938, loss: 1.524 (data_loss: 1.524, reg_loss: 0.000), lr: 0.0010000
validation, acc: 0.930, loss: 1.531


Epoch 4/10: 100%|████████████████████| 1563/1563 [00:24<00:00, 65.04step/s]


time: 24.04s, acc: 0.947, loss: 1.514 (data_loss: 1.514, reg_loss: 0.000), lr: 0.0010000
validation, acc: 0.942, loss: 1.519


Epoch 5/10: 100%|████████████████████| 1563/1563 [00:24<00:00, 64.96step/s]


time: 24.06s, acc: 0.949, loss: 1.510 (data_loss: 1.510, reg_loss: 0.000), lr: 0.0010000
validation, acc: 0.944, loss: 1.517


Epoch 6/10: 100%|████████████████████| 1563/1563 [00:24<00:00, 64.78step/s]


time: 24.14s, acc: 0.929, loss: 1.507 (data_loss: 1.507, reg_loss: 0.000), lr: 0.0010000
validation, acc: 0.925, loss: 1.536


Epoch 7/10: 100%|████████████████████| 1563/1563 [00:24<00:00, 64.41step/s]


time: 24.28s, acc: 0.965, loss: 1.504 (data_loss: 1.504, reg_loss: 0.000), lr: 0.0010000
validation, acc: 0.959, loss: 1.502


Epoch 8/10: 100%|████████████████████| 1563/1563 [00:23<00:00, 67.40step/s]


time: 23.21s, acc: 0.966, loss: 1.503 (data_loss: 1.503, reg_loss: 0.000), lr: 0.0010000
validation, acc: 0.958, loss: 1.503


Epoch 9/10: 100%|████████████████████| 1563/1563 [00:20<00:00, 78.01step/s]


time: 20.04s, acc: 0.970, loss: 1.499 (data_loss: 1.499, reg_loss: 0.000), lr: 0.0010000
validation, acc: 0.963, loss: 1.498


Epoch 10/10: 100%|████████████████████| 1563/1563 [00:20<00:00, 77.78step/s]


time: 20.10s, acc: 0.968, loss: 1.498 (data_loss: 1.498, reg_loss: 0.000), lr: 0.0010000
validation, acc: 0.962, loss: 1.499


In [10]:
predictions = model.predict(test_images)
print(predictions)

[[0.08533674 0.08533674 0.08533674 ... 0.23196932 0.08533674 0.08533674]
 [0.08533674 0.08533674 0.23196932 ... 0.08533674 0.08533674 0.08533674]
 [0.08533674 0.23196932 0.08533674 ... 0.08533674 0.08533674 0.08533674]
 ...
 [0.08533674 0.08533674 0.08533674 ... 0.08533674 0.08533674 0.08533674]
 [0.08533674 0.08533674 0.08533674 ... 0.08533674 0.08533674 0.08533674]
 [0.08533674 0.08533674 0.08533674 ... 0.08533674 0.08533674 0.08533674]]
